import os

GMAIL_USERNAME = os.environ.get("GMAIL_USERNAME")
GMAIL_PASSWORD = os.environ.get("GMAIL_PASSWORD")
SMARTBILL_TOKEN = os.environ.get("SMARTBILL_TOKEN")
POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")

CREDENTIALS = {
    "GMAIL_USERNAME": GMAIL_USERNAME,
    "GMAIL_PASSWORD": GMAIL_PASSWORD,
    "SMARTBILL_TOKEN": SMARTBILL_TOKEN,
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
}